### ISSUE TITLE
error: 'plc_hw_status' undeclared

### ISSUE THREAD

**Issue by Felipeasg** [nucleron/RTE#2]
Hi there,

I am trying to build tye **yaplc_runtime** to flash the stm32f4discovery, as I can't use codeblocks to build the project, I am creating my own makefile, but when I try to build the compiler can't find the variable '**plc_hw_status**'.

I am using the following bsp: **RTE/src/bsp/stm32f4/**

This variable apper to be defined in the [file](https://github.com/nucleron/RTE/blob/master/src/bsp/nuc-247-0/plc_tick.c#L52) but as extern.

The definition  **PLC_HW_ERR_DEADLINE** also appears not to be declared.

Do I need to implement my own sistick handler? 

Thanks in advance.. 
The project is really fantastic...

**Comment by nucleron** [comment]
First of all, you should open a project with code::blocks, or alternatively you can use cb2make.

>The definition PLC_HW_ERR_DEADLINE appears not to be declared.
https://github.com/nucleron/RTE/blob/6c5bf32d4f37ceb1162789835c58475cab69b7ab/src/plc_diag.h#L12

>This variable apper to be defined in the file but as extern.
This file is not used and it should be deleted. The file in use is https://github.com/nucleron/RTE/blob/master/src/bsp/common/plc_tick.c

>Do I need to implement my own sistick handler?
No, you don't have to and you shouldn't do this.

**Comment by Felipeasg** [comment]
Thanks by the fast answer

I really can't build the project with the **codeblocks** and neither **cb3make**, due to my lack of ability to work with the **codeblock IDE**. The IDE dont find the compiler **"armnoneeabigcc"**, and I can't configure the compiller to build the project properly.

Them inspired by your comments and reading the file **yaplc-runtime.cbp** to verify file dependencies (to build just what is needed) I have create an project based on Makefile hosted [here](https://github.com/Felipeasg/f4disc_rte).

Finally I can build the project but if I use your original linker script [stm32f4disco-rte.ld](https://github.com/nucleron/RTE/blob/master/src/bsp/stm32f4/stm32f4disco-rte.ld) (that have the memory area **app_flash**) the ld gives the following error:

`: region `rom' overflowed by 1268 bytes`

Them I increased the rom section 2k as bellow and decreased the app_flash 2k, and everythink work.

`
MEMORY
{
    rom       (rx)  : ORIGIN = 0x08000000, LENGTH = 34K 
    app_flash (rx)  : ORIGIN = 0x08008000, LENGTH = 990K
    ram       (rwx) : ORIGIN = 0x20000000, LENGTH = 8K
    appram    (rwx) : ORIGIN = 0x20002000, LENGTH = 120K
}
`

My question is: 
Do you have the similar problem with codeblocks?

**Comment by nucleron** [comment]
>The IDE dont find the compiler "armnoneeabigcc", and I can't configure the compiller to build the project properly.

See https://github.com/nucleron/YAPLC/blob/master/BuildOnLinux.md
and https://stackoverflow.com/questions/5604183/adding-compiler-to-codeblocks/5604380

>if I use your original linker script stm32f4disco-rte.ld (that have the memory area app_flash) the ld gives the following error (using the -Os flag): region rom' overflowed by 1268 bytes

You are doing something wrong! 
F4 discovery project fits to 20k of flash with correct toolcahin options!

I think this is because you used other toolchain version than we or you have missed some compiler/linker option (e.g. -nostdlib).

Try to use these options:
 * compiler -g and https://github.com/nucleron/RTE/blob/master/projects/yaplc-runtime/yaplc-runtime.cbp#L32

* linker -s and https://github.com/nucleron/RTE/blob/master/projects/yaplc-runtime/yaplc-runtime.cbp#L52

BTW: Linker should be g++, not gcc 

>Can the change in the app_flash have side effects?
You should adjust memories in *-app.ld file!

**Comment by Felipeasg** [comment]
I realized in **.cbp** that you are using **gcc-arm-none-eabi-4_9** and I am using the **gcc gcc-arm-none-eabi-7-2017-q4-major**. Changing the compiler really the project fit to 20K flash.

Finally I was able to build the [yaplc-runtime](https://github.com/nucleron/RTE/tree/master/projects/yaplc-runtime) project with code blocks, after ajust the trick to adjust the path to search libc.a in the **armv7e-m/fpu** directory.

I also flash the firmware in the F4 Discovery board and changed the hse to 8mhz since the yaplc-runtime project was setted to work with hse of 16mhz. The new build was tested tooggling one led in the board.

I think that I can close this issue and begin some tests flashing applications generated by **YAPLC/IDE**.

What do you need to use g++ to link the binary and not gcc?

Thanks again.
